config/routes.rb
MyGists::Application.routes.draw do
  get "gists/search"
  resources :gists
  root 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base
		def self.search(search)
	if search
		find(:all, :conditions => ['lang LIKE ?', "%#{search}%"])
	else
		limit(0)
	end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

	# ...

	def show 
		@community = Community.find(params[:id])
		@users = @community.users
		@ressources = Ressource.paginate(:page => params[:page], :per_page => 5)
	end


	# ...
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]




  # GET /gists
  # GET /gists.json
  def index
    get_and_show_gists
  end

  def get_and_show_gists 
    @gists = Gist.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end


  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  def search
    @gists = Gist.search(params[:lang])
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
<%
  all_lexers = Pygments.lexers.flatten.select.with_index(offset = 0) { |x,i| i % 2 == 0 }.sort 
  all_lexers = all_lexers.delete_if { |x| x =~ /.\s./ }
  all_lexers = all_lexers.map { |x| x.downcase }
%>


  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
      <tr>
   <td> <%= f.label :Kod %></td>
 </tr>
 <tr>
  <td><%= f.text_area :snippet, :class => "area" %></td>

</tr>
<tr>
      <td><%= f.label :Opis %></td>

     
  </tr>
  <tr>
 <td><%= f.text_area :description, :class => "area" %></td>
  </tr>
  <tr>
    <td><%= f.label :Język %></td>
  </tr>
    <tr><td><%= f.select :lang, all_lexers %></td>
  </tr>
</table>

    
    
 

  <div class="actions">
    <%= f.submit 'Gotowe', :class => 'btn btn-large btn-default' %>
  </div>
<% end %>

app/views/gists/_gist.html.erb
<div class="gistBox">
  <div class="codeBox">
    <%= raw Pygments.highlight(gist.snippet.length > 30 ? gist.snippet[0,90] + "" : gist.snippet, lexer: gist.lang) %>
  </div>
  <div class="langBox">
          <%= gist.lang %>
  </div>
  <div class="descriptionBox">
          <%= gist.description %>
  </div>


  <div class="buttonBox">
          <%= link_to 'Pokaż', gist, :class => "btn  btn-success" %>
          <%= link_to 'Edytuj', edit_gist_path(gist), :class => "btn btn-warning" %>
         <%= link_to 'Usuń', gist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
  </div>
</div> <!-- gistBox -->

app/views/gists/edit.html.erb
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
     <nav>
      <ul class="nav pull-left">
        <li>
          <a href="/gists">MyGists</a>
        </li>
        <li>
          <a href="http://www.github.com/waveq/MyGists">Projekt na githubie</a>
        </li>
        <li>
          <a href="/gists/new">Quick add</a>
        </li>
    </nav>
  
  </div>
</div>
<div class="center hero-unit">
	<h1>Edycja</h1>
<%= render 'form' %>
<hr />
<%= link_to 'Pokaż', @gist, :class =>"btn btn-large btn-success" %>
<%= link_to 'Powrót', gists_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/gists/index.html.erb
<div class="all" >
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <nav>
      <ul class="nav pull-left">
        <li>
          <a href="/gists">MyGists</a>
        </li>
        <li>
          <a href="http://www.github.com/waveq/MyGists">Projekt na githubie</a>
        </li>
        <li>
          <a href="/gists/new">Quick add</a>
        </li>
        <li class="divider-vertical" />
      </ul>
      <ul class="nav pull-right hidden-xs">
        <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
          <div class="form-group">
            <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip},
             params[:lang]))%>
           </div>
           <button type="submit" class="btn btn-default">Search</button>
         </form>
       </ul>
    </nav>
  
  </div>
</div>

</div>

<div class="center hero-unit">
  <%= link_to 'Dodaj', new_gist_path, :class => "btn btn-large btn-prime"  %>
  <div id="gists-list">
       <%= render @gists %>
  </div>
</div>
 

<div id="infinite-scrolling" disabled="true">
    <%= will_paginate %>
</div>

app/views/gists/index.js.erb
$('#gists-list').append('<%= j render @gists %>');

<% if @gists.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @gists %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/gists/new.html.erb
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <nav>
      <ul class="nav pull-left">
        <li>
          <a href="/gists">MyGists</a>
        </li>
        <li>
          <a href="http://www.github.com/waveq/MyGists">Projekt na githubie</a>
        </li>
        <li>
          <a href="/gists/new">Quick add</a>
        </li>
    </nav>
  
  </div>
</div>

<div class="center hero-unit">
	<h1>Nowy gist</h1>
<%= render 'form' %>
<hr />
<%= link_to 'Powrót', gists_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/gists/search.html.erb
<div class="all" >
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <nav>
      <ul class="nav pull-left">
        <li>
          <a href="/gists">MyGists</a>
        </li>
        <li>
          <a href="http://www.github.com/waveq/MyGists">Projekt na githubie</a>
        </li>
        <li>
          <a href="/gists/new">Quick add</a>
        </li>
        <li class="divider-vertical" />
      </ul>
      <ul class="nav pull-right hidden-xs">
        <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
          <div class="form-group">
            <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip},
             params[:lang]))%>
           </div>
           <button type="submit" class="btn btn-default">Search</button>
         </form>
       </ul>
    </nav>
  
  </div>
</div>

<div class="center hero-unit">
        

<h1>Znalezione gisty:</h1><br />

    <% @gists.each do |gist| %>
<div class="gistBox">


  <div class="codeBox">
    <%= raw Pygments.highlight(gist.snippet.length > 30 ? gist.snippet[0,90] + "" : gist.snippet, lexer: gist.lang) %>
  </div>
  <div class="langBox">
          <%= gist.lang %>
  </div>
  <div class="descriptionBox">
          <%= gist.description %>
  </div>
  <div class="buttonBox">
          <%= link_to 'Pokaż', gist, :class => "btn  btn-success" %>
          <%= link_to 'Edytuj', edit_gist_path(gist), :class => "btn btn-warning" %>
         <%= link_to 'Usuń', gist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
  </div>
</div> <!-- gistBox -->
    <% end %>
</div> <!-- gitstsBox -->

app/views/gists/show.html.erb
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
        <nav>
      <ul class="nav pull-left">
        <li>
          <a href="/gists">MyGists</a>
        </li>
          <li>
          <a href="http://www.github.com/waveq/MyGists">Projekt na githubie</a>
        </li>
         </li>
          <li>
          <a href="/gists/new">Quick add</a>
        </li>

    </nav>
  
  </div>

</div>
<div class="center hero-unit">
  <div class="showBox">
	<h1>Język: <%= @gist.lang %>
  <div class="panel-heading"><h3>Kod:</h3></div>
  <div class="panel-body">
<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
<div class="panel-foot">
<h3>Description:</h3>
<div class="showDescriptionBox" >
  <p><%= @gist.description %></p>
</div>
</div>
</div>
<div class="alert alert-info">
  <%= notice %>
</div>
</div>
<hr />
<%= link_to 'Edytuj', edit_gist_path(@gist), :class => "btn btn-large btn-warning" %> 
<%= link_to 'Wróć', gists_path, :class => "btn btn-large btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>